version: "3"

services:
  nginx:
    container_name: phalcon-php-nginx
    build:
      context: .
      dockerfile: .docker/docker-nginx.dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - phalcon-php-network
    links:
      - php

  php:
      container_name: php
      image: php:7.2-fpm
      volumes:
        - .:/usr/share/nginx/html
      networks:
        - phalcon-php-network
      build:
        context: .
        dockerfile: .docker/docker-php.dockerfile
networks:
  phalcon-php-network:
    driver: bridge